"""
One-time SQLite migration for SkillNova assessment configurations.

Run from the backend directory:

    python migrate_assessment_attempts.py

Optional:

    python migrate_assessment_attempts.py skillnova.db

This migration preserves existing assessment attempts, responses and results,
but changes the AssessmentAttempt uniqueness rule from:

    student + assessment

to:

    student + assessment + configuration_key

The configuration key is generated by the assessment API from:
role + profile year + test type + difficulty.

Existing attempts are preserved. If an old attempt has a question carrying a
SkillNova configuration marker, that marker is used. Otherwise the attempt is
given a unique legacy key so it does not block a new configuration.
"""

from __future__ import annotations

import re
import shutil
import sqlite3
import sys
from datetime import datetime
from pathlib import Path


DEFAULT_DB = Path("skillnova.db")
CONFIG_RE = re.compile(r"\|cfg=([^|\]]+)")


def backup_database(db_path: Path) -> Path:
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup = db_path.with_name(f"{db_path.stem}_before_assessment_config_{stamp}{db_path.suffix}")
    shutil.copy2(db_path, backup)
    return backup


def main() -> None:
    db_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DB

    if not db_path.exists():
        raise SystemExit(f"Database not found: {db_path.resolve()}")

    backup = backup_database(db_path)
    print(f"Backup created: {backup.resolve()}")

    con = sqlite3.connect(str(db_path))
    con.execute("PRAGMA foreign_keys=OFF")

    try:
        cols = {
            row[1]
            for row in con.execute("PRAGMA table_info(assessment_attempts)").fetchall()
        }

        if "configuration_key" in cols:
            print("assessment_attempts.configuration_key already exists.")
            print("No migration needed.")
            return

        old_rows = con.execute(
            """
            SELECT
                id,
                student_id,
                assessment_id,
                status,
                score,
                total_questions,
                started_at,
                submitted_at
            FROM assessment_attempts
            ORDER BY id
            """
        ).fetchall()

        # Recover configuration IDs from existing question markers where possible.
        recovered: dict[int, str] = {}

        for row in old_rows:
            attempt_id = row[0]
            category_row = con.execute(
                """
                SELECT q.category
                FROM assessment_responses r
                JOIN assessment_questions q
                  ON q.id = r.question_id
                WHERE r.attempt_id = ?
                ORDER BY r.id
                LIMIT 1
                """,
                (attempt_id,),
            ).fetchone()

            category = category_row[0] if category_row else ""
            match = CONFIG_RE.search(str(category or ""))
            if match:
                recovered[attempt_id] = match.group(1)

        con.execute(
            """
            CREATE TABLE assessment_attempts_new (
                id INTEGER NOT NULL PRIMARY KEY,
                student_id INTEGER NOT NULL,
                assessment_id INTEGER NOT NULL,
                status VARCHAR(30) NOT NULL DEFAULT 'IN_PROGRESS',
                score INTEGER NOT NULL DEFAULT 0,
                total_questions INTEGER NOT NULL DEFAULT 0,
                configuration_key VARCHAR(100) NOT NULL DEFAULT 'legacy',
                started_at DATETIME,
                submitted_at DATETIME,
                FOREIGN KEY(student_id) REFERENCES users(id) ON DELETE CASCADE,
                FOREIGN KEY(assessment_id) REFERENCES assessments(id) ON DELETE CASCADE,
                CONSTRAINT uq_student_assessment_config_attempt
                    UNIQUE(student_id, assessment_id, configuration_key)
            )
            """
        )

        used_keys: set[tuple[int, int, str]] = set()

        for row in old_rows:
            (
                attempt_id,
                student_id,
                assessment_id,
                status,
                score,
                total_questions,
                started_at,
                submitted_at,
            ) = row

            config_key = recovered.get(attempt_id) or f"legacy-{attempt_id}"

            # Never let two historical rows collide, even if malformed data
            # contains duplicate IDs/markers.
            base_key = config_key
            counter = 2
            while (student_id, assessment_id, config_key) in used_keys:
                config_key = f"{base_key}-{counter}"
                counter += 1

            used_keys.add((student_id, assessment_id, config_key))

            con.execute(
                """
                INSERT INTO assessment_attempts_new (
                    id,
                    student_id,
                    assessment_id,
                    status,
                    score,
                    total_questions,
                    configuration_key,
                    started_at,
                    submitted_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    attempt_id,
                    student_id,
                    assessment_id,
                    status,
                    score,
                    total_questions,
                    config_key,
                    started_at,
                    submitted_at,
                ),
            )

        con.execute("DROP TABLE assessment_attempts")
        con.execute("ALTER TABLE assessment_attempts_new RENAME TO assessment_attempts")

        con.execute(
            """
            CREATE INDEX ix_assessment_attempts_configuration_key
            ON assessment_attempts(configuration_key)
            """
        )
        con.execute(
            """
            CREATE INDEX ix_assessment_attempts_student_id
            ON assessment_attempts(student_id)
            """
        )
        con.execute(
            """
            CREATE INDEX ix_assessment_attempts_assessment_id
            ON assessment_attempts(assessment_id)
            """
        )

        con.commit()

        print(f"Migrated {len(old_rows)} existing assessment attempt(s).")
        print("New uniqueness: student + assessment + configuration_key.")
        print("Migration completed successfully.")

    except Exception:
        con.rollback()
        raise
    finally:
        con.execute("PRAGMA foreign_keys=ON")
        con.close()


if __name__ == "__main__":
    main()
